manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: cb9c573b534dcb52ee8cf6b2cec6cb880e841301
      import: app/west.yml
  self:
    path: config
