manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/ayroblu
      #url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: PR-2188
      # revision: main
      import: app/west.yml
  self:
    path: config
